"""update image_url

Revision ID: 74f582248c8b
Revises: 4374ec39360f
Create Date: 2025-01-07 21:59:04.024246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f582248c8b'
down_revision = '4374ec39360f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
